USE meile;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Amazon%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Hetzner%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "OVH%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Digitalocean%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Contabo%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Akamai%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Adcd%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Brainstorm%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Chociz%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Colocrossing%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Dedipath%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Leaseweb%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Madcity%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Reliablesite%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Reliablesite%") as temp SET ns.datacenter = True, isp_type = "hosting" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "AT&T%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Bell%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Artnet%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Cedric%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Charter%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Comcast%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Compa%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Inform%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Locaweb%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "M Sat Cable%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Nos Comunicacoes%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Orange Polska%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Pe Fedinyak%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Skylink%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Societe%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Suddenlink%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Swisscom%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Telef%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Tmnet%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Verizon%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;
UPDATE node_score AS ns, (SELECT node_address FROM node_score WHERE isp LIKE "Vodafone%") as temp SET ns.datacenter = False, isp_type = "residential" WHERE temp.node_address = ns.node_address;

